# Generated by Django 5.0 on 2025-11-29 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorCursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='creador_alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='creador_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cursos_tomado',
            field=models.ManyToManyField(blank=True, related_name='alumnos_cursos', to='gestorCursos.curso'),
        ),
    ]
