# Generated by Django 5.0 on 2025-11-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorCursos', '0002_alumno_creador_alumno_curso_creador_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre']},
        ),
    ]
