# Generated by Django 4.2.30 on 2026-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorCursos', '0003_alter_alumno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
