# Generated by Django 5.0 on 2025-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Docente', 'Docente'), ('Administrador', 'Administrador')], max_length=15),
        ),
    ]
